/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.mcmcg.media.workflow.swf;

import com.amazonaws.services.simpleworkflow.flow.DataConverter;
import com.amazonaws.services.simpleworkflow.flow.StartWorkflowOptions;
import com.amazonaws.services.simpleworkflow.flow.WorkflowClientBase;
import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.generic.GenericWorkflowClient;
import com.amazonaws.services.simpleworkflow.model.WorkflowExecution;
import com.amazonaws.services.simpleworkflow.model.WorkflowType;

class IngestionWorkflowClientImpl extends WorkflowClientBase implements IngestionWorkflowClient {

    public IngestionWorkflowClientImpl(WorkflowExecution workflowExecution, WorkflowType workflowType,  
            StartWorkflowOptions options, DataConverter dataConverter, GenericWorkflowClient genericClient) {
        super(workflowExecution, workflowType, options, dataConverter, genericClient);
    }
    
    @Override
    public final Promise<Void> execute(String filename, String messageId) { 
        return execute(Promise.asPromise(filename), Promise.asPromise(messageId), (StartWorkflowOptions)null);
    }
    
    @Override
    public final Promise<Void> execute(String filename, String messageId, Promise<?>... waitFor) {
        return execute(Promise.asPromise(filename), Promise.asPromise(messageId), (StartWorkflowOptions)null, waitFor);
    }
    
    
    @Override
    
    public final Promise<Void> execute(String filename, String messageId, StartWorkflowOptions optionsOverride, Promise<?>... waitFor) {
        return execute(Promise.asPromise(filename), Promise.asPromise(messageId), optionsOverride, waitFor);
    }

    @Override
    public final Promise<Void> execute(Promise<String> filename, Promise<String> messageId) {
        return execute(filename, messageId, (StartWorkflowOptions)null);
    }

    @Override
    public final Promise<Void> execute(Promise<String> filename, Promise<String> messageId, Promise<?>... waitFor) {
        return execute(filename, messageId, (StartWorkflowOptions)null, waitFor);
    }

    @Override
    
    @SuppressWarnings({ "unchecked", "rawtypes" })
    public final Promise<Void> execute(Promise<String> filename, Promise<String> messageId, StartWorkflowOptions optionsOverride, Promise<?>... waitFor) {
        Promise[] _input_ = new Promise[2];
        _input_[0] = filename;
        _input_[1] = messageId;
        return (Promise) startWorkflowExecution(_input_, optionsOverride, Void.class, waitFor);
    }
    	

}