/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.mcmcg.media.workflow.swf;

import com.amazonaws.services.simpleworkflow.flow.core.AndPromise;
import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.core.Task;
import com.amazonaws.services.simpleworkflow.flow.DataConverter;
import com.amazonaws.services.simpleworkflow.flow.StartWorkflowOptions;
import com.amazonaws.services.simpleworkflow.flow.WorkflowSelfClientBase;
import com.amazonaws.services.simpleworkflow.flow.generic.ContinueAsNewWorkflowExecutionParameters;
import com.amazonaws.services.simpleworkflow.flow.generic.GenericWorkflowClient;

public class IngestionWorkflowSelfClientImpl extends WorkflowSelfClientBase implements IngestionWorkflowSelfClient {

    public IngestionWorkflowSelfClientImpl() {
        this(null, new com.amazonaws.services.simpleworkflow.flow.JsonDataConverter(), null);
    }

    public IngestionWorkflowSelfClientImpl(GenericWorkflowClient genericClient) {
        this(genericClient, new com.amazonaws.services.simpleworkflow.flow.JsonDataConverter(), null);
    }

    public IngestionWorkflowSelfClientImpl(GenericWorkflowClient genericClient, 
            DataConverter dataConverter, StartWorkflowOptions schedulingOptions) {
            
        super(genericClient, dataConverter, schedulingOptions);
    }

    @Override
    public final void execute(String filename, String messageId) { 
        executeImpl(Promise.asPromise(filename), Promise.asPromise(messageId), (StartWorkflowOptions)null);
    }

    @Override
    public final void execute(String filename, String messageId, Promise<?>... waitFor) { 
        executeImpl(Promise.asPromise(filename), Promise.asPromise(messageId), (StartWorkflowOptions)null, waitFor);
    }
    
    @Override
    public final void execute(String filename, String messageId, StartWorkflowOptions optionsOverride, Promise<?>... waitFor) {
        executeImpl(Promise.asPromise(filename), Promise.asPromise(messageId), optionsOverride, waitFor);
    }
    
    @Override
    public final void execute(Promise<String> filename, Promise<String> messageId) {
        executeImpl(filename, messageId, (StartWorkflowOptions)null);
    }

    @Override
    public final void execute(Promise<String> filename, Promise<String> messageId, Promise<?>... waitFor) {
        executeImpl(filename, messageId, (StartWorkflowOptions)null, waitFor);
    }

    @Override
    public final void execute(Promise<String> filename, Promise<String> messageId, StartWorkflowOptions optionsOverride, Promise<?>... waitFor) {
        executeImpl(filename, messageId, optionsOverride, waitFor);
    }
    
    protected void executeImpl(final Promise<String> filename, final Promise<String> messageId, final StartWorkflowOptions schedulingOptionsOverride, Promise<?>... waitFor) {
        new Task(new Promise[] { filename, messageId, new AndPromise(waitFor) }) {
    		@Override
			protected void doExecute() throws Throwable {
                ContinueAsNewWorkflowExecutionParameters _parameters_ = new ContinueAsNewWorkflowExecutionParameters();
                Object[] _input_ = new Object[2];
                _input_[0] = filename.get();
                _input_[1] = messageId.get();
                String _stringInput_ = dataConverter.toData(_input_);
				_parameters_.setInput(_stringInput_);
				_parameters_ = _parameters_.createContinueAsNewParametersFromOptions(schedulingOptions, schedulingOptionsOverride);
                
                if (genericClient == null) {
                    genericClient = decisionContextProvider.getDecisionContext().getWorkflowClient();
                }
                genericClient.continueAsNewOnCompletion(_parameters_);
			}
		};
    }
}