/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.mcmcg.media.workflow.swf;

import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.StartWorkflowOptions;
import com.amazonaws.services.simpleworkflow.flow.WorkflowSelfClient;

/**
 * Generated from {@link com.mcmcg.media.workflow.swf.IngestionWorkflow}. 
 * Used to continue a workflow execution as a new run.
 * Must be used from a worklfow scope. 
 */
public interface IngestionWorkflowSelfClient extends WorkflowSelfClient
{

    /**
     * Generated from {@link com.mcmcg.media.workflow.swf.IngestionWorkflow#execute}
     */
    void execute(String filename, String messageId);

    /**
     * Generated from {@link com.mcmcg.media.workflow.swf.IngestionWorkflow#execute}
     */
    void execute(String filename, String messageId, Promise<?>... waitFor);

    /**
     * Generated from {@link com.mcmcg.media.workflow.swf.IngestionWorkflow#execute}
     */
    void execute(String filename, String messageId, StartWorkflowOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.mcmcg.media.workflow.swf.IngestionWorkflow#execute}
     */
    void execute(Promise<String> filename, Promise<String> messageId);

    /**
     * Generated from {@link com.mcmcg.media.workflow.swf.IngestionWorkflow#execute}
     */
    void execute(Promise<String> filename, Promise<String> messageId, Promise<?>... waitFor);

    /**
     * Generated from {@link com.mcmcg.media.workflow.swf.IngestionWorkflow#execute}
     */
    void execute(Promise<String> filename, Promise<String> messageId, StartWorkflowOptions optionsOverride, Promise<?>... waitFor);
}