/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.mcmcg.media.workflow.swf;

import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.StartWorkflowOptions;
import com.amazonaws.services.simpleworkflow.flow.WorkflowClient;

/**
 * Generated from {@link com.mcmcg.media.workflow.swf.IngestionWorkflow}. 
 * Used to invoke child workflows asynchronously from parent workflow code.
 * Created through {@link IngestionWorkflowClientFactory#getClient}.
 * <p>
 * When running outside of the scope of a workflow use {@link IngestionWorkflowClientExternal} instead.
 */
public interface IngestionWorkflowClient extends WorkflowClient
{

    /**
     * Generated from {@link com.mcmcg.media.workflow.swf.IngestionWorkflow#execute}
     */
    Promise<Void> execute(String filename, String messageId);

    /**
     * Generated from {@link com.mcmcg.media.workflow.swf.IngestionWorkflow#execute}
     */
    Promise<Void> execute(String filename, String messageId, Promise<?>... waitFor);

    /**
     * Generated from {@link com.mcmcg.media.workflow.swf.IngestionWorkflow#execute}
     */
    Promise<Void> execute(String filename, String messageId, StartWorkflowOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.mcmcg.media.workflow.swf.IngestionWorkflow#execute}
     */
    Promise<Void> execute(Promise<String> filename, Promise<String> messageId);

    /**
     * Generated from {@link com.mcmcg.media.workflow.swf.IngestionWorkflow#execute}
     */
    Promise<Void> execute(Promise<String> filename, Promise<String> messageId, Promise<?>... waitFor);

    /**
     * Generated from {@link com.mcmcg.media.workflow.swf.IngestionWorkflow#execute}
     */
    Promise<Void> execute(Promise<String> filename, Promise<String> messageId, StartWorkflowOptions optionsOverride, Promise<?>... waitFor);

}