/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.mcmcg.media.workflow.swf;

import com.amazonaws.services.simpleworkflow.flow.WorkflowClientFactory;

/**
 * Generated from {@link com.mcmcg.media.workflow.swf.IngestionWorkflow}. 
 * Used to create workflow clients for use within the scope of a parent workflow.
 * <p>
 * When running outside of the scope of a workflow use {@link IngestionWorkflowClientExternalFactory} instead.
 */
public interface IngestionWorkflowClientFactory extends WorkflowClientFactory<IngestionWorkflowClient> {
    
}